### ISSUE TITLE
Not able to understand 'let context = (UIApplication.shared.delegate as! AppDelegate).persistentContainer.viewContext'

### ISSUE THREAD

**Issue by shravanik2405** [shravanik2405/Todoey#2]
Why can't access the variable 'context' from AppDelegate as we normally do, with syntax something like this
let context = AppDelegate.persistentContainer.viewContext

**Comment by paragdulam** [comment]
let context = AppDelegate.persistentContainer.viewContext

AppDelegate is a class name and if you check your code, the  persistentContainer variable is not declared static. If it was a static variable then you could have the ability to access it like you mentioned. In case you dont know what static variables are, read about them. Also persistentContainer is a LAZY and a MEMBER VARIABLE which can be accessed only when you create an instance of AppDelegate class Hence the correct syntax would be:

let appDelegate = UIApplication.shared.delegate as! AppDelegate
appDelegate.persistentContainer.viewContext

**Comment by paragdulam** [comment]
Reopen this issue in case you find any difficulties. Call if necessary
